
services:
  flask_welcome_2025:
    build: .
    ports:
      - "5009:5000"
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/app
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
